apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: oc-hibernate
  namespace: openshift-cloud-credential-operator
spec:
  secretRef:
    name: oc-hibernate
    namespace: kube-system
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AWSProviderSpec
    statementEntries:
    - effect: Allow
      action:
      - ec2:DescribeInstances
      - ec2:DescribeTags
      - ec2:StartInstances
      - ec2:StopInstances
      resource: "*"
