- hosts: localhost
  connection: local
  vars:
    cluster_id: '*'
  tasks:
    #- name: Get Control Plane EC2 Instances
    #  amazon.aws.ec2_instance_info:
    #    filters:
    #      "tag:Name": "{{cluster_id}}-master-*"
    #  register: control_plane_instances

    - name: Stop Control Plane EC2 Instances
      amazon.aws.ec2_instance:
        filters:
          "tag:Name": "{{cluster_id}}-master-*"
        state: stopped
        wait: true
        wait_timeout: 300

    # - name: Get Worker EC2 Instances
    #   amazon.aws.ec2_instance_info:
    #     filters:
    #       "tag:Name": "{{cluster_id}}-worker-*"
    #   register: worker_instances

    - name: Stop Worker EC2 Instances
      amazon.aws.ec2_instance:
        filters:
          "tag:Name": "{{cluster_id}}-worker-*"
        state: stopped
        wait: true
        wait_timeout: 300
