- name: Start OpenShift cluster
  hosts: localhost
  connection: local
  vars:
    aws_profile: default
  tasks:
    - name: Start Control Plane EC2 Instances
      amazon.aws.ec2_instance:
        filters:
          "tag:Name": "{{cluster_id}}-master-*"
        profile: "{{ aws_profile }}"
        state: started # Wait for health checks to report OK
        wait: true
        wait_timeout: 300

    - name: Start Worker EC2 Instances
      amazon.aws.ec2_instance:
        filters:
          "tag:Name": "{{cluster_id}}-worker-*"
        profile: "{{ aws_profile }}"
        state: started # Wait for health checks to report OK
        wait: true
        wait_timeout: 300
