- hosts: localhost
  connection: local
  tasks:
    - name: Stop Worker EC2 Instances
      amazon.aws.ec2_instance:
        filters:
          "tag:Name": "{{cluster_id}}-worker-*"
        state: stopped
        wait: true
        wait_timeout: 300

    - name: Stop Control Plane EC2 Instances
      amazon.aws.ec2_instance:
        filters:
          "tag:Name": "{{cluster_id}}-master-*"
        state: stopped
        wait: true
        wait_timeout: 300
